# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='location',
            field=models.CharField(choices=[('US', 'United States'), ('DE', 'Germany'), ('JP', 'Japan'), ('FR', 'France')], max_length=2),
        ),
    ]
