# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0003_auto_20160412_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerprofile',
            name='camera_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
