# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import imager_images.models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20160414_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img_file',
            field=models.ImageField(upload_to=imager_images.models.image_path),
        ),
    ]
